apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  PG_USER_EMAIL: c3VwZXJtYW5AZ29vZ2xlLmNvbQ== # superman@google.com
  DB_PASSWORD: RXN0b0VzVW5QYXNzV29yZFNlY3JldG8= # EstoEsUnPassWordSecreto